#!/usr/bin/env python3

import subprocess
from pathlib import Path

home_dir = Path('~').expanduser()
bkps_dir = home_dir / 'Dropbox' / 'backups'
shared_bkp_dir = bkps_dir / 'laptop'
res = subprocess.run('hostname', stdout=subprocess.PIPE)
hostname = res.stdout.rstrip().decode('utf-8')
host_bkp_dir = bkps_dir / hostname
excl_suffixes = {'.desktop', '.vcf', '.xz', '.EXE', '.txt'}
excl_names = {'signature', 'scripts', 'mc', 'mutt', 'Pictures', 'keyboard',
                'services', 'crypto', 'unison'}

def filter_files_from(bkp_path):
    return [path for path in bkp_path.glob('*') if '_' not in path.name and
                                                    path.name not in excl_names and
                                                    path.suffix not in excl_suffixes]

host_files = filter_files_from(host_bkp_dir)
host_filenames = {path.name for path in host_files}
shared_files = [path for path in filter_files_from(shared_bkp_dir) if path.name not in host_filenames]
host_files.extend(shared_files)

for path in host_files:
        target = home_dir / ('.%s' % path.name)
        print('symlink %s -> %s' % (target, path))
        # path.symlink_to(target)
